version: '3.8'

services:
  plash:
    image: nginx/unit:1.29.0-minimal
    container_name: plash
    restart: always
    volumes:
      - ./unit/:/docker-entrypoint.d/
      - ./dist/:/www/:ro
    ports:
      - "6123:443"
